### PR TITLE
Update Caddyfile.development

### PR DESCRIPTION
**Pull request by jerbob**

### CODE REVIEW

**Review by david-cooke — APPROVED** [review]

**Review by jchristgit — CHANGES_REQUESTED** [review]
What a great commit message! This does not respect @thebeanogamer's comment on the last PR though.

**Comment by jerbob** [comment]
Thanks @jchristgit, I have fixed this problem.

**Review by jchristgit — APPROVED** [review]
Thanks!

**Review by 404dcd — APPROVED** [review]
Looks good to me! Glad we all helped to make this wonderful piece of software.

**Review by jchristgit — APPROVED** [review]
Thanks!

**Pull request merged**
